### ISSUE TITLE
documentation mismatch

### ISSUE THREAD

**Issue by rumski20** [azavea/python-sld#14]
The `Rule.create_filter` is looking for `==` when doing a PropertyIsEqualTo comparitor. However, the [documentation](https://github.com/azavea/python-sld/blob/70e363782b39249bc9512a78dbbc45aaee52aaf5/sld/__init__.py#L1059) states that `=` is acceptable.

This had me looking around for a while. :(

**Comment by dzwarg** [comment]
@rumski20 Thanks! Will fix.

**Comment by dzwarg** [comment]
@kshepard This is fixed in #19, and can be closed.
